### ISSUE TITLE
Only grabs 4 songs

### ISSUE THREAD

**Issue by Darkfard** [gmenih341/8TracksDownloader#1]
Hi, are you still working on this? It only grabs 4 songs and then it stops.
Thanks!

**Comment by gmenih** [comment]
Unfortunately, 8Tracks only allows 3 skips per playlist. When I made this, this wasn't implemented in their API, which allowed for infinite track skips, to get the JSON of every track in a playlist. 

They updated their API to fix this issue, and patch this program.
